// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotelService.proto

package com.example.demo;

public interface HotelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.HotelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string hotelName = 2;</code>
   */
  java.lang.String getHotelName();
  /**
   * <code>string hotelName = 2;</code>
   */
  com.google.protobuf.ByteString
      getHotelNameBytes();
}
