# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hotelService_pb2 as hotelService__pb2


class HotelServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getHotel = channel.unary_unary(
        '/com.example.demo.HotelService/getHotel',
        request_serializer=hotelService__pb2.HotelRequest.SerializeToString,
        response_deserializer=hotelService__pb2.HotelResponse.FromString,
        )


class HotelServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getHotel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HotelServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getHotel': grpc.unary_unary_rpc_method_handler(
          servicer.getHotel,
          request_deserializer=hotelService__pb2.HotelRequest.FromString,
          response_serializer=hotelService__pb2.HotelResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.example.demo.HotelService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
